// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sync_service.proto
// Protobuf C++ Version: 5.29.3

#include "sync_service.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace blp {

inline constexpr SyncRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        slave_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        last_message_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR SyncRequest::SyncRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SyncRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SyncRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SyncRequestDefaultTypeInternal() {}
  union {
    SyncRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SyncRequestDefaultTypeInternal _SyncRequest_default_instance_;

inline constexpr DataItem::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        message_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        value_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR DataItem::DataItem(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct DataItemDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DataItemDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DataItemDefaultTypeInternal() {}
  union {
    DataItem _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DataItemDefaultTypeInternal _DataItem_default_instance_;

inline constexpr SyncResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        items_{},
        is_full_sync_{false},
        has_more_{false} {}

template <typename>
PROTOBUF_CONSTEXPR SyncResponse::SyncResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SyncResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SyncResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SyncResponseDefaultTypeInternal() {}
  union {
    SyncResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SyncResponseDefaultTypeInternal _SyncResponse_default_instance_;
}  // namespace blp
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_sync_5fservice_2eproto = nullptr;
static const ::_pb::ServiceDescriptor*
    file_level_service_descriptors_sync_5fservice_2eproto[1];
const ::uint32_t
    TableStruct_sync_5fservice_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        PROTOBUF_FIELD_OFFSET(::blp::SyncRequest, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::blp::SyncRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::blp::SyncRequest, _impl_.slave_id_),
        PROTOBUF_FIELD_OFFSET(::blp::SyncRequest, _impl_.last_message_id_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::blp::DataItem, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::blp::DataItem, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::blp::DataItem, _impl_.message_id_),
        PROTOBUF_FIELD_OFFSET(::blp::DataItem, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::blp::DataItem, _impl_.value_),
        0,
        1,
        2,
        PROTOBUF_FIELD_OFFSET(::blp::SyncResponse, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::blp::SyncResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::blp::SyncResponse, _impl_.items_),
        PROTOBUF_FIELD_OFFSET(::blp::SyncResponse, _impl_.is_full_sync_),
        PROTOBUF_FIELD_OFFSET(::blp::SyncResponse, _impl_.has_more_),
        ~0u,
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, 10, -1, sizeof(::blp::SyncRequest)},
        {12, 23, -1, sizeof(::blp::DataItem)},
        {26, 37, -1, sizeof(::blp::SyncResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::blp::_SyncRequest_default_instance_._instance,
    &::blp::_DataItem_default_instance_._instance,
    &::blp::_SyncResponse_default_instance_._instance,
};
const char descriptor_table_protodef_sync_5fservice_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022sync_service.proto\022\003blp\"8\n\013SyncRequest"
    "\022\020\n\010slave_id\030\001 \002(\t\022\027\n\017last_message_id\030\002 "
    "\001(\t\":\n\010DataItem\022\022\n\nmessage_id\030\001 \002(\t\022\013\n\003k"
    "ey\030\002 \002(\t\022\r\n\005value\030\003 \002(\t\"T\n\014SyncResponse\022"
    "\034\n\005items\030\001 \003(\0132\r.blp.DataItem\022\024\n\014is_full"
    "_sync\030\002 \001(\010\022\020\n\010has_more\030\003 \001(\0102>\n\013SyncSer"
    "vice\022/\n\010SyncData\022\020.blp.SyncRequest\032\021.blp"
    ".SyncResponseB\003\200\001\001"
};
static ::absl::once_flag descriptor_table_sync_5fservice_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_sync_5fservice_2eproto = {
    false,
    false,
    298,
    descriptor_table_protodef_sync_5fservice_2eproto,
    "sync_service.proto",
    &descriptor_table_sync_5fservice_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_sync_5fservice_2eproto::offsets,
    file_level_enum_descriptors_sync_5fservice_2eproto,
    file_level_service_descriptors_sync_5fservice_2eproto,
};
namespace blp {
// ===================================================================

class SyncRequest::_Internal {
 public:
  using HasBits =
      decltype(std::declval<SyncRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SyncRequest, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

SyncRequest::SyncRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:blp.SyncRequest)
}
inline PROTOBUF_NDEBUG_INLINE SyncRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::blp::SyncRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        slave_id_(arena, from.slave_id_),
        last_message_id_(arena, from.last_message_id_) {}

SyncRequest::SyncRequest(
    ::google::protobuf::Arena* arena,
    const SyncRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SyncRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:blp.SyncRequest)
}
inline PROTOBUF_NDEBUG_INLINE SyncRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        slave_id_(arena),
        last_message_id_(arena) {}

inline void SyncRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SyncRequest::~SyncRequest() {
  // @@protoc_insertion_point(destructor:blp.SyncRequest)
  SharedDtor(*this);
}
inline void SyncRequest::SharedDtor(MessageLite& self) {
  SyncRequest& this_ = static_cast<SyncRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.slave_id_.Destroy();
  this_._impl_.last_message_id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* SyncRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SyncRequest(arena);
}
constexpr auto SyncRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(SyncRequest),
                                            alignof(SyncRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SyncRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SyncRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        SyncRequest::IsInitializedImpl,
        &SyncRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SyncRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SyncRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SyncRequest>(), &SyncRequest::ByteSizeLong,
            &SyncRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SyncRequest, _impl_._cached_size_),
        false,
    },
    &SyncRequest::kDescriptorMethods,
    &descriptor_table_sync_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SyncRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 47, 2> SyncRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SyncRequest, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::blp::SyncRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional string last_message_id = 2;
    {::_pbi::TcParser::FastSS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(SyncRequest, _impl_.last_message_id_)}},
    // required string slave_id = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(SyncRequest, _impl_.slave_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required string slave_id = 1;
    {PROTOBUF_FIELD_OFFSET(SyncRequest, _impl_.slave_id_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // optional string last_message_id = 2;
    {PROTOBUF_FIELD_OFFSET(SyncRequest, _impl_.last_message_id_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\17\10\17\0\0\0\0\0"
    "blp.SyncRequest"
    "slave_id"
    "last_message_id"
  }},
};

PROTOBUF_NOINLINE void SyncRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:blp.SyncRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.slave_id_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.last_message_id_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SyncRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SyncRequest& this_ = static_cast<const SyncRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SyncRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SyncRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:blp.SyncRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // required string slave_id = 1;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_slave_id();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "blp.SyncRequest.slave_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // optional string last_message_id = 2;
          if (cached_has_bits & 0x00000002u) {
            const std::string& _s = this_._internal_last_message_id();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "blp.SyncRequest.last_message_id");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:blp.SyncRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SyncRequest::ByteSizeLong(const MessageLite& base) {
          const SyncRequest& this_ = static_cast<const SyncRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SyncRequest::ByteSizeLong() const {
          const SyncRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:blp.SyncRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // required string slave_id = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_slave_id());
            }
          }
           {
            // optional string last_message_id = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_last_message_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SyncRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SyncRequest*>(&to_msg);
  auto& from = static_cast<const SyncRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:blp.SyncRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_slave_id(from._internal_slave_id());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_last_message_id(from._internal_last_message_id());
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SyncRequest::CopyFrom(const SyncRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:blp.SyncRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool SyncRequest::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const SyncRequest&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void SyncRequest::InternalSwap(SyncRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.slave_id_, &other->_impl_.slave_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.last_message_id_, &other->_impl_.last_message_id_, arena);
}

::google::protobuf::Metadata SyncRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DataItem::_Internal {
 public:
  using HasBits =
      decltype(std::declval<DataItem>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(DataItem, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000007) ^ 0x00000007) != 0;
  }
};

DataItem::DataItem(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:blp.DataItem)
}
inline PROTOBUF_NDEBUG_INLINE DataItem::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::blp::DataItem& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        message_id_(arena, from.message_id_),
        key_(arena, from.key_),
        value_(arena, from.value_) {}

DataItem::DataItem(
    ::google::protobuf::Arena* arena,
    const DataItem& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  DataItem* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:blp.DataItem)
}
inline PROTOBUF_NDEBUG_INLINE DataItem::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        message_id_(arena),
        key_(arena),
        value_(arena) {}

inline void DataItem::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
DataItem::~DataItem() {
  // @@protoc_insertion_point(destructor:blp.DataItem)
  SharedDtor(*this);
}
inline void DataItem::SharedDtor(MessageLite& self) {
  DataItem& this_ = static_cast<DataItem&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_id_.Destroy();
  this_._impl_.key_.Destroy();
  this_._impl_.value_.Destroy();
  this_._impl_.~Impl_();
}

inline void* DataItem::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) DataItem(arena);
}
constexpr auto DataItem::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(DataItem),
                                            alignof(DataItem));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull DataItem::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_DataItem_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        DataItem::IsInitializedImpl,
        &DataItem::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<DataItem>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &DataItem::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<DataItem>(), &DataItem::ByteSizeLong,
            &DataItem::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(DataItem, _impl_._cached_size_),
        false,
    },
    &DataItem::kDescriptorMethods,
    &descriptor_table_sync_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* DataItem::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 39, 2> DataItem::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(DataItem, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::blp::DataItem>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // required string message_id = 1;
    {::_pbi::TcParser::FastSS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(DataItem, _impl_.message_id_)}},
    // required string key = 2;
    {::_pbi::TcParser::FastSS1,
     {18, 1, 0, PROTOBUF_FIELD_OFFSET(DataItem, _impl_.key_)}},
    // required string value = 3;
    {::_pbi::TcParser::FastSS1,
     {26, 2, 0, PROTOBUF_FIELD_OFFSET(DataItem, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required string message_id = 1;
    {PROTOBUF_FIELD_OFFSET(DataItem, _impl_.message_id_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required string key = 2;
    {PROTOBUF_FIELD_OFFSET(DataItem, _impl_.key_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
    // required string value = 3;
    {PROTOBUF_FIELD_OFFSET(DataItem, _impl_.value_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kRawString | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\14\12\3\5\0\0\0\0"
    "blp.DataItem"
    "message_id"
    "key"
    "value"
  }},
};

PROTOBUF_NOINLINE void DataItem::Clear() {
// @@protoc_insertion_point(message_clear_start:blp.DataItem)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _impl_.message_id_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      _impl_.key_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000004u) {
      _impl_.value_.ClearNonDefaultToEmpty();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* DataItem::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const DataItem& this_ = static_cast<const DataItem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* DataItem::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const DataItem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:blp.DataItem)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // required string message_id = 1;
          if (cached_has_bits & 0x00000001u) {
            const std::string& _s = this_._internal_message_id();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "blp.DataItem.message_id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // required string key = 2;
          if (cached_has_bits & 0x00000002u) {
            const std::string& _s = this_._internal_key();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "blp.DataItem.key");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // required string value = 3;
          if (cached_has_bits & 0x00000004u) {
            const std::string& _s = this_._internal_value();
            ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(_s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormat::SERIALIZE,
                                        "blp.DataItem.value");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:blp.DataItem)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t DataItem::ByteSizeLong(const MessageLite& base) {
          const DataItem& this_ = static_cast<const DataItem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t DataItem::ByteSizeLong() const {
          const DataItem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:blp.DataItem)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000007u) {
            // required string message_id = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_message_id());
            }
            // required string key = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_key());
            }
            // required string value = 3;
            if (cached_has_bits & 0x00000004u) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_value());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void DataItem::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DataItem*>(&to_msg);
  auto& from = static_cast<const DataItem&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:blp.DataItem)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_message_id(from._internal_message_id());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_internal_set_key(from._internal_key());
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_internal_set_value(from._internal_value());
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DataItem::CopyFrom(const DataItem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:blp.DataItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool DataItem::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const DataItem&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void DataItem::InternalSwap(DataItem* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_id_, &other->_impl_.message_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.key_, &other->_impl_.key_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, &other->_impl_.value_, arena);
}

::google::protobuf::Metadata DataItem::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SyncResponse::_Internal {
 public:
  using HasBits =
      decltype(std::declval<SyncResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(SyncResponse, _impl_._has_bits_);
};

SyncResponse::SyncResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:blp.SyncResponse)
}
inline PROTOBUF_NDEBUG_INLINE SyncResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::blp::SyncResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        items_{visibility, arena, from.items_} {}

SyncResponse::SyncResponse(
    ::google::protobuf::Arena* arena,
    const SyncResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SyncResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, is_full_sync_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, is_full_sync_),
           offsetof(Impl_, has_more_) -
               offsetof(Impl_, is_full_sync_) +
               sizeof(Impl_::has_more_));

  // @@protoc_insertion_point(copy_constructor:blp.SyncResponse)
}
inline PROTOBUF_NDEBUG_INLINE SyncResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        items_{visibility, arena} {}

inline void SyncResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, is_full_sync_),
           0,
           offsetof(Impl_, has_more_) -
               offsetof(Impl_, is_full_sync_) +
               sizeof(Impl_::has_more_));
}
SyncResponse::~SyncResponse() {
  // @@protoc_insertion_point(destructor:blp.SyncResponse)
  SharedDtor(*this);
}
inline void SyncResponse::SharedDtor(MessageLite& self) {
  SyncResponse& this_ = static_cast<SyncResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* SyncResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SyncResponse(arena);
}
constexpr auto SyncResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(SyncResponse, _impl_.items_) +
          decltype(SyncResponse::_impl_.items_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(SyncResponse), alignof(SyncResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&SyncResponse::PlacementNew_,
                                 sizeof(SyncResponse),
                                 alignof(SyncResponse));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SyncResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SyncResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        SyncResponse::IsInitializedImpl,
        &SyncResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SyncResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SyncResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SyncResponse>(), &SyncResponse::ByteSizeLong,
            &SyncResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SyncResponse, _impl_._cached_size_),
        false,
    },
    &SyncResponse::kDescriptorMethods,
    &descriptor_table_sync_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SyncResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2> SyncResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(SyncResponse, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::blp::SyncResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated .blp.DataItem items = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(SyncResponse, _impl_.items_)}},
    // optional bool is_full_sync = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SyncResponse, _impl_.is_full_sync_), 0>(),
     {16, 0, 0, PROTOBUF_FIELD_OFFSET(SyncResponse, _impl_.is_full_sync_)}},
    // optional bool has_more = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SyncResponse, _impl_.has_more_), 1>(),
     {24, 1, 0, PROTOBUF_FIELD_OFFSET(SyncResponse, _impl_.has_more_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .blp.DataItem items = 1;
    {PROTOBUF_FIELD_OFFSET(SyncResponse, _impl_.items_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // optional bool is_full_sync = 2;
    {PROTOBUF_FIELD_OFFSET(SyncResponse, _impl_.is_full_sync_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional bool has_more = 3;
    {PROTOBUF_FIELD_OFFSET(SyncResponse, _impl_.has_more_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }}, {{
    {::_pbi::TcParser::GetTable<::blp::DataItem>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void SyncResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:blp.SyncResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.items_.Clear();
  ::memset(&_impl_.is_full_sync_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.has_more_) -
      reinterpret_cast<char*>(&_impl_.is_full_sync_)) + sizeof(_impl_.has_more_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SyncResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SyncResponse& this_ = static_cast<const SyncResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SyncResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SyncResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:blp.SyncResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .blp.DataItem items = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_items_size());
               i < n; i++) {
            const auto& repfield = this_._internal_items().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // optional bool is_full_sync = 2;
          if (cached_has_bits & 0x00000001u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_is_full_sync(), target);
          }

          // optional bool has_more = 3;
          if (cached_has_bits & 0x00000002u) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                3, this_._internal_has_more(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:blp.SyncResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SyncResponse::ByteSizeLong(const MessageLite& base) {
          const SyncResponse& this_ = static_cast<const SyncResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SyncResponse::ByteSizeLong() const {
          const SyncResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:blp.SyncResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .blp.DataItem items = 1;
            {
              total_size += 1UL * this_._internal_items_size();
              for (const auto& msg : this_._internal_items()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // optional bool is_full_sync = 2;
            if (cached_has_bits & 0x00000001u) {
              total_size += 2;
            }
            // optional bool has_more = 3;
            if (cached_has_bits & 0x00000002u) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SyncResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SyncResponse*>(&to_msg);
  auto& from = static_cast<const SyncResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:blp.SyncResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_items()->MergeFrom(
      from._internal_items());
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.is_full_sync_ = from._impl_.is_full_sync_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.has_more_ = from._impl_.has_more_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SyncResponse::CopyFrom(const SyncResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:blp.SyncResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool SyncResponse::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const SyncResponse&>(msg);
  if (!::google::protobuf::internal::AllAreInitialized(this_._internal_items()))
    return false;
  return true;
}

void SyncResponse::InternalSwap(SyncResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.items_.InternalSwap(&other->_impl_.items_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SyncResponse, _impl_.has_more_)
      + sizeof(SyncResponse::_impl_.has_more_)
      - PROTOBUF_FIELD_OFFSET(SyncResponse, _impl_.is_full_sync_)>(
          reinterpret_cast<char*>(&_impl_.is_full_sync_),
          reinterpret_cast<char*>(&other->_impl_.is_full_sync_));
}

::google::protobuf::Metadata SyncResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

const ::google::protobuf::ServiceDescriptor* SyncService::descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_sync_5fservice_2eproto);
  return file_level_service_descriptors_sync_5fservice_2eproto[0];
}

const ::google::protobuf::ServiceDescriptor* SyncService::GetDescriptor() {
  return descriptor();
}

void SyncService::SyncData(::google::protobuf::RpcController* controller,
                         const ::blp::SyncRequest*, ::blp::SyncResponse*, ::google::protobuf::Closure* done) {
  controller->SetFailed("Method SyncData() not implemented.");
  done->Run();
}

void SyncService::CallMethod(
    const ::google::protobuf::MethodDescriptor* method,
    ::google::protobuf::RpcController* controller,
    const ::google::protobuf::Message* request,
    ::google::protobuf::Message* response, ::google::protobuf::Closure* done) {
  ABSL_DCHECK_EQ(method->service(), file_level_service_descriptors_sync_5fservice_2eproto[0]);
  switch (method->index()) {
    case 0:
      this->SyncData(controller,
                   ::google::protobuf::DownCastMessage<::blp::SyncRequest>(request),
                   ::google::protobuf::DownCastMessage<::blp::SyncResponse>(response),
                   done);
      break;

    default:
      ABSL_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& SyncService::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  ABSL_DCHECK_EQ(method->service(), descriptor());
  switch (method->index()) {
    case 0:
      return ::blp::SyncRequest::default_instance();

    default:
      ABSL_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
                  ->GetPrototype(method->input_type());
  }
}

const ::google::protobuf::Message& SyncService::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  ABSL_DCHECK_EQ(method->service(), descriptor());
  switch (method->index()) {
    case 0:
      return ::blp::SyncResponse::default_instance();

    default:
      ABSL_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
                  ->GetPrototype(method->output_type());
  }
}

SyncService_Stub::SyncService_Stub(::google::protobuf::RpcChannel* channel)
    : channel_(channel), owns_channel_(false) {}

SyncService_Stub::SyncService_Stub(
    ::google::protobuf::RpcChannel* channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
    : channel_(channel),
      owns_channel_(ownership ==
                    ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}

SyncService_Stub::~SyncService_Stub() {
  if (owns_channel_) delete channel_;
}

void SyncService_Stub::SyncData(::google::protobuf::RpcController* controller,
                              const ::blp::SyncRequest* request,
                              ::blp::SyncResponse* response, ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0), controller,
                       request, response, done);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace blp
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_sync_5fservice_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
